name: JosePlugin
main: com.josemarcellio.joseplugin.JosePlugin
version: 1.0.0
author: JoseMarcellio
api-version: 1.21
commands:
  dailyreward:
    aliases:
      - dailyrewards
      - dreward
      - drewards
  party:
    aliases:
      - partys
      - parties
  playerwarp:
    aliases:
      - playerwarps
      - pwarp
      - pwarps
  job:
    aliases:
      - jobs
  troll:
    aliases:
      - trolls
  playtime:
    aliases: []
  silentkick:
    aliases:
      - silent