name: JosePlugin
main: com.josemarcellio.joseplugin.JosePlugin
version: 1.0.0
author: JoseMarcellio
api-version: 1.21
load: STARTUP
loadbefore:
  - Essentials
commands:
  dailyreward:
    aliases:
      - dailyrewards
      - dreward
      - drewards
  party:
    aliases:
      - partys
      - parties
  playerwarp:
    aliases:
      - playerwarps
      - pwarp
      - pwarps
  job:
    aliases:
      - jobs
  troll:
    aliases:
      - trolls